name: Build

on:
  push:
    branches: [ master, splitux-*, main ]
  pull_request:
    branches: [ master, splitux-*, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson clang glslang libcap wlroots0.18 \
            sdl2 vulkan-headers libx11 libxmu libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols benchmark \
            xorg-xwayland pipewire cmake \
            libavif libheif aom rav1e libdecor libxdamage \
            luajit

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with gcc
        run: |
          export CC=gcc CXX=g++
          meson build-gcc/ -Dinput_emulation=disabled --auto-features=enabled -Dbuildtype=release
          ninja -C build-gcc/
          strip build-gcc/src/gamescope build-gcc/src/gamescopereaper build-gcc/src/gamescopectl

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gamescope-splitux-build
          path: |
            build-gcc/src/gamescope
            build-gcc/src/gamescopereaper
            build-gcc/src/gamescopectl
          retention-days: 7
