name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson glslang libcap wlroots0.18 \
            sdl2 vulkan-headers libx11 libxmu libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols benchmark \
            xorg-xwayland pipewire cmake \
            libavif libheif aom rav1e libdecor libxdamage \
            luajit zip

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          export CC=gcc CXX=g++
          meson build/ -Dinput_emulation=disabled -Denable_openvr_support=false --auto-features=enabled
          ninja -C build/
          strip build/src/gamescope build/src/gamescopectl build/src/gamescopereaper

      - name: Package
        run: |
          mkdir -p release/bin
          cp build/src/gamescope release/bin/
          cp build/src/gamescopectl release/bin/
          cp build/src/gamescopereaper release/bin/
          cd release
          zip -r ../gamescope-splitux-${{ github.ref_name }}.zip bin/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: gamescope-splitux-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
